// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Szakdolgozat.DataAccess;

namespace Szakdoga.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211101142442_DB")]
    partial class DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Szakdolgozat.Models.Felulvizsgalat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("penztargepid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Felulvizsgalatok");
                });

            modelBuilder.Entity("Szakdolgozat.Models.Penztargep", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("beuzemeles")
                        .HasColumnType("datetime2");

                    b.Property<int>("szemelyId")
                        .HasColumnType("int");

                    b.Property<int>("telephelyId")
                        .HasColumnType("int");

                    b.Property<int>("tipusId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Penztargepek");
                });

            modelBuilder.Entity("Szakdolgozat.Models.Szekhely", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("hsz")
                        .HasColumnType("int");

                    b.Property<int>("irsz")
                        .HasColumnType("int");

                    b.Property<string>("utca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("varos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Szekhelyek");
                });

            modelBuilder.Entity("Szakdolgozat.Models.Szemely", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adoszam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("szekhelyId")
                        .HasColumnType("int");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Szemelyek");
                });

            modelBuilder.Entity("Szakdolgozat.Models.Telephely", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("hsz")
                        .HasColumnType("int");

                    b.Property<int>("irsz")
                        .HasColumnType("int");

                    b.Property<string>("utca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("varos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Telephelyek");
                });
#pragma warning restore 612, 618
        }
    }
}
